import turtle
#create dividing line to split the canvas for two puzzles
divider = turtle.Turtle()
divider.left(90)
divider.forward(300)
divider.left(180)
divider.forward(600)

#recreate image of two spirals using 2 Turtle objects
spiral_left = turtle.Turtle()
spiral_right = turtle.Turtle()
#set starting location and position for each spiral "pen"
spiral_right.penup()
spiral_right.forward(300)
spiral_right.pendown()
spiral_left.penup()
spiral_left.forward(300)
spiral_left.pendown()
spiral_left.left(180)
#draw left spiral
spiral_left.forward(200)
spiral_left.right(90)
spiral_left.forward(200)
spiral_left.right(90)
spiral_left.forward(200)
spiral_left.right(90)
spiral_left.forward(150)
spiral_left.right(90)
spiral_left.forward(150)
spiral_left.right(90)
spiral_left.forward(100)
spiral_left.right(90)
spiral_left.forward(100)
spiral_left.right(90)
spiral_left.forward(50)
spiral_left.right(90)
spiral_left.forward(50)

#draw right spiral
spiral_right.forward(200)
spiral_right.left(90)
spiral_right.forward(200)
spiral_right.left(90)
spiral_right.forward(200)
spiral_right.left(90)
spiral_right.forward(150)
spiral_right.left(90)
spiral_right.forward(150)
spiral_right.left(90)
spiral_right.forward(100)
spiral_right.left(90)
spiral_right.forward(100)
spiral_right.left(90)
spiral_right.forward(50)
spiral_right.left(90)
spiral_right.forward(50)

#recreate image of four spirals using 4 Turtle objects
upper_left = turtle.Turtle()
upper_right = turtle.Turtle()
lower_left = turtle.Turtle()
lower_right = turtle.Turtle()

#set starting location and position for each spiral "pen"
upper_left.left(180)
upper_left.penup()
upper_left.forward(300)
upper_left.pendown()
lower_left.left(180)
lower_left.penup()
lower_left.forward(300)
lower_left.pendown()
upper_right.left(180)
upper_right.penup()
upper_right.forward(300)
upper_right.left(180)
upper_right.pendown()
lower_right.left(180)
lower_right.penup()
lower_right.forward(300)
lower_right.left(180)
lower_right.pendown()

#draw upper left spiral
upper_left.forward(200)
upper_left.right(90)
upper_left.forward(200)
upper_left.right(90)
upper_left.forward(200)
upper_left.right(90)
upper_left.forward(150)
upper_left.right(90)
upper_left.forward(150)
upper_left.right(90)
upper_left.forward(100)
upper_left.right(90)
upper_left.forward(100)
upper_left.right(90)
upper_left.forward(50)
upper_left.right(90)
upper_left.forward(50)

#draw upper right spiral
upper_right.forward(200)
upper_right.left(90)
upper_right.forward(200)
upper_right.left(90)
upper_right.forward(200)
upper_right.left(90)
upper_right.forward(150)
upper_right.left(90)
upper_right.forward(150)
upper_right.left(90)
upper_right.forward(100)
upper_right.left(90)
upper_right.forward(100)
upper_right.left(90)
upper_right.forward(50)
upper_right.left(90)
upper_right.forward(50)

#draw lower left spiral
lower_left.forward(200)
lower_left.left(90)
lower_left.forward(200)
lower_left.left(90)
lower_left.forward(200)
lower_left.left(90)
lower_left.forward(150)
lower_left.left(90)
lower_left.forward(150)
lower_left.left(90)
lower_left.forward(100)
lower_left.left(90)
lower_left.forward(100)
lower_left.left(90)
lower_left.forward(50)
lower_left.left(90)
lower_left.forward(50)

#draw lower right spiral
lower_right.forward(200)
lower_right.right(90)
lower_right.forward(200)
lower_right.right(90)
lower_right.forward(200)
lower_right.right(90)
lower_right.forward(150)
lower_right.right(90)
lower_right.forward(150)
lower_right.right(90)
lower_right.forward(100)
lower_right.right(90)
lower_right.forward(100)
lower_right.right(90)
lower_right.forward(50)
lower_right.right(90)
lower_right.forward(50)

turtle.done()
